CC = gcc -std=gnu11 
LDFLAGS = -lm -lrt
CFLAGS = -Wall -O2

OBJS = obj/1-16.o obj/1-17.o obj/1-18.o obj/1-20.o obj/1-21.o obj/1-22.o obj/1-23.o obj/1-24.o obj/2-1.o obj/2-3.o obj/2-4.o obj/2-6.o obj/3-2.o obj/3-3.o obj/4-1.o obj/4-2.o obj/4-3.o obj/4-12.o obj/5-3.o obj/btest.o obj/5-4.o obj/5-7.o obj/5-9.o obj/5-13.o obj/5-17.o obj/6-1.o obj/6-3.o obj/6-3-w-hashtable.o obj/6-5.o obj/7-2.o obj/7-3.o obj/8-1.o obj/8-3.o obj/8-4.o obj/8-5.o obj/8-6.o obj/8-7.o obj/hashtable_example.o obj/hashtable.o obj/common.o obj/sorted_tree.o obj/sorted_tree_example.o obj/sorted_tree_generic_example.o obj/ini.o obj/ini_example.o

%.o: %.c
$(CC) $(CFLAGS) -o $@ -c $^

clean:
rm $(OBJS) run_exercise
